- name: hack yum repo to install httpd-tools
  shell: >
    sed -ri  's#(baseurl.*7)\..*(/.*/x86_64/)#\1\2#g' /etc/yum.repos.d/hpecoe.repo 
- name: install httpd-tools
  yum: name={{item}} state=latest
  with_items:
    - "httpd-tools"
    - "epel-release"
- name: install jq
  yum: name=jq state=latest

# generate meta-data.tar.gz
- name: delete suite-data folder if exist
  file: dest=/home/admin/itsma-suite-data-kit state=absent
- name: get suite-data code form github
  git:
    repo: https://github.houston.softwaregrp.net/SMA-RnD/itsma-suite-data.git 
    dest: /home/admin/itsma-suite-data-kit
    version: master 
    depth: 1
    force: yes
- shell: >
    cd /home/admin/itsma-suite-data-kit/itsma/config &&
    mv feature/ suite_feature &&
    mkdir itsma &&
    mv suite_feature/* itsma/ &&
    mv itsma/ suite_feature/ &&
    sed  -i '/"suite"{{':'}} "itsma",/i\    "suiteInfoList"{{':'}} [{' suiteinfo.json &&
    sed -i '$ a\]}' suiteinfo.json &&
    sed -ri 's#(.*image":\s{0,}").*(",)#\1{{ installer_registry }}:{{ installer_tag }}\2#g' suiteinfo.json &&
    for i in `ls ./suite_feature/itsma/ `; do cat ./suite_feature/itsma/$i/itsma_suitefeatures.$i.json |jq '.images = [{"image": "heapster:v1.5.2"}]' |jq '.feature_sets[].images = [{"image": "heapster:v1.5.2"}]' > tmp.$$.json && mv -f tmp.$$.json ./suite_feature/itsma/$i/itsma_suitefeatures.$i.json; done &&
    tar -zcf meta-data.tar.gz * &&
    mv meta-data.tar.gz /home/admin/meta-data.tar.gz

- name: generate config.json from template
  template: src=config-templ.json dest=/home/admin/config.json

- name: Download and install the infra service installer
  get_url:
    url: "{{ itom_base_infra_installer }}"
    dest: /home/admin/{{ itom_base_infra_zip_name }}
    timeout: 600
- unarchive: src=/home/admin/{{ itom_base_infra_zip_name }} dest=/home/admin/ copy=no mode=0777
- shell: mv /home/admin/{{ itom_base_infra }}* /home/admin/{{ itom_base_infra }}
 
#- debug: msg="ansible_host {{ ansible_host }}"
#- debug: msg="worker_nodes {{ worker_nodes }}"
#- debug: msg="master nodes {{ master }}"
- replace: dest=/home/admin/{{ itom_base_infra }}/install.properties regexp='^REGISTRY_ORGNAME.*$' replace='REGISTRY_ORGNAME=itsma'
- replace: dest=/home/admin/{{ itom_base_infra }}/install.properties regexp="^#THINPOOL_DEVICE.*$" replace='THINPOOL_DEVICE="/dev/mapper/docker-thinpool , /dev/mapper/docker--bootstrap-thinpool"'
  when: thinpool == "true"
- group: name=itsma gid=1999
- user: name=itsma group=itsma uid=1999
- shell: >
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{global_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{db_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{db_nfs_expose1}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{db_nfs_expose2}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{smartanalytics_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{propel_rabbitmq_0_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{propel_rabbitmq_1_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{propel_rabbitmq_2_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{cdf_db_vol_single_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{rabbitmq_infra_rabbitmq_0_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{rabbitmq_infra_rabbitmq_1_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{rabbitmq_infra_rabbitmq_2_expose}} &&
    /home/admin/{{ itom_base_infra }}/scripts/setupNFS.sh {{cdf_db_backup_nfs_expose}} &&
    /home/admin/{{ itom_base_infra }}/install -m /home/admin/meta-data.tar.gz -c /home/admin/config.json -P "1Qaz2wsx," -D "shc-harbor-dev.hpeswlab.net:443" --registry-orgname "itsma" -e "full-cdf" &&
    echo "source <(kubectl completion bash)" >> /etc/profile
# tag core platform with suitekit when installed by suitekit
- copy: dest=/opt/kubernetes/do_not_touch mode=600 content="suitekit\n"
- name: include vars
  get_url:
    url: "https://raw.github.houston.softwaregrp.net/SMA-RnD/suite-tools/master/alias-tool/alias.sh"
    dest: /etc/profile.d/
    mode: 0644

