- hosts: localhost
  become: true
  become_user: root
  become_method: sudo 
  gather_facts: False
  pre_tasks:
    - set_fact: dockerconfigjson="ewoJImF1dGhzIjogewoJCSJzaGMtZGV2b3BzLWhhcmJvci5pdHNtYS14LmlvIjogewoJCQkiYXV0aCI6ICJZMmxmZFhObGNqcFFZWE56ZDI5eVpERT0iCgkJfQoJfQp9"
    - file: state=directory dest={{suite_config_template_path}}/output/yaml_templates group=itsma owner=itsma
    - name: Hack the credentials for private registry
      copy:
        dest: "{{suite_config_template_path}}/deployer-secret.yml"
        owner: itsma
        group: itsma
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: registrypullsecret
            namespace: core
          data:
            .dockerconfigjson: {{dockerconfigjson}} 
          type: kubernetes.io/dockerconfigjson
          ---
    - name: create deployer secret with kubectl create
      shell: >
         kubectl  create -f {{suite_config_template_path}}/deployer-secret.yml

    - name: generate secert yaml
      copy:
        dest: "{{suite_config_template_path}}/output/yaml_templates/suite_secret.yaml"
        content: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: registrypullsecret
            #namespace: ${namespace}
            namespace: itsma1
          data:
            .dockerconfigjson: {{dockerconfigjson}}
          type: kubernetes.io/dockerconfigjson
          ---
    - name: create jdbc folder on global-pv
      file: state=directory dest={{global_nfs_expose}}/jdbc
  roles:
    - { role: new-suite-install}
    - { role: deploy-suite}
